apiVersion: v1
entries:
  kvdi:
  - apiVersion: v2
    appVersion: v0.1.1
    created: "2020-12-11T10:47:14.1879134+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13667a42c4be002e2980ca0625bb4a7399b171ee73a1f0fe1a3c4de7bdc377ba
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.1.tgz
    version: v0.1.1
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2020-12-11T10:47:14.1869987+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 75b553c4fea1303767743944a8e470f6d56784b85f8a0698edc5e786fc3c05ac
    name: kvdi
    type: application
    urls:
    - kvdi-v0.1.0.tgz
    version: v0.1.0
  - apiVersion: v2
    appVersion: v0.0.30
    created: "2020-12-11T10:47:14.1830568+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 34ab066222a956dce6cc8e564acd819d3d3faa87f2eacac16110f35022f4b6b2
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.30.tgz
    version: v0.0.30
  - apiVersion: v2
    appVersion: v0.0.29
    created: "2020-12-11T10:47:14.1815566+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 5bee9003c4d317c3c2cb9bc74b6141f03f7721012b16bdda2559f89e363ae48b
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.29.tgz
    version: v0.0.29
  - apiVersion: v2
    appVersion: v0.0.28
    created: "2020-12-11T10:47:14.1785723+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 9f0cc8effbf06960996e0e65eb108551d7c50be646cc7bd31d80c4560a9d1628
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.28.tgz
    version: v0.0.28
  - apiVersion: v2
    appVersion: v0.0.27
    created: "2020-12-11T10:47:14.1774466+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: e7a3bab9249c88e5b621725e5974cc3219318b6d16d1a8baedf29bc46453d5cb
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.27.tgz
    version: v0.0.27
  - apiVersion: v2
    appVersion: v0.0.26
    created: "2020-12-11T10:47:14.1765857+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: c321c1d2344c5b10ceb50d964e3ac12e30a32248720dcf3c45aef1563ba09f3d
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.26.tgz
    version: v0.0.26
  - apiVersion: v2
    appVersion: v0.0.25
    created: "2020-12-11T10:47:14.1757251+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 47c25986182fe3b77b403504180527b4a78d30ad33a2879905fdc458fc2992e0
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.25.tgz
    version: v0.0.25
  - apiVersion: v2
    appVersion: v0.0.24
    created: "2020-12-11T10:47:14.1748106+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: a47b3edbefc5f3bda87fb93469f7e84bc046bcd85257b83f96a16ec570e1def9
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.24.tgz
    version: v0.0.24
  - apiVersion: v2
    appVersion: v0.0.23
    created: "2020-12-11T10:47:14.1738577+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 8008d086d4adfd113e6fce84519d64801f989b6e7ccaa98b8fcf68a2eda6f616
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.23.tgz
    version: v0.0.23
  - apiVersion: v2
    appVersion: v0.0.22
    created: "2020-12-11T10:47:14.1730048+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 1e153630ce220c52777bb4bf1ac69a997141d907cd385444d947261ddbbb6df2
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.22.tgz
    version: v0.0.22
  - apiVersion: v2
    appVersion: v0.0.21
    created: "2020-12-11T10:47:14.1721407+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 266fb9d68a9f027f4274aacc302dc5d86273be0c3fe8f93f8d07a5ae3190c522
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.21.tgz
    version: v0.0.21
  - apiVersion: v2
    appVersion: v0.0.20
    created: "2020-12-11T10:47:14.1712639+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: a0228cb115992dd6332041d52fecea6d03c1bed004088fb3176e6c7e25f42e2b
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.20.tgz
    version: v0.0.20
  - apiVersion: v2
    appVersion: v0.0.19
    created: "2020-12-11T10:47:14.1703359+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 15da1226e9b81f0d090249a644e1d8d83d827fd180d47e576cf36e71b533a1e8
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.19.tgz
    version: v0.0.19
  - apiVersion: v2
    appVersion: v0.0.18
    created: "2020-12-11T10:47:14.1693343+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: a18c90ad5592dbb6e4d81ba2cadacdb75098fefd55e5a3bff88ec336e0669a4d
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.18.tgz
    version: v0.0.18
  - apiVersion: v2
    appVersion: v0.0.17
    created: "2020-12-11T10:47:14.167026+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 13a4993c221e1b95bfb45473981bd50e31f0f5f72ffddabf38e45f49be963e8c
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.17.tgz
    version: v0.0.17
  - apiVersion: v2
    appVersion: v0.0.16
    created: "2020-12-11T10:47:14.1661833+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 63ae78f0f336cf904ef14a1bf130e25a3842cfb4b51e23d283007a8756ef45c6
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.16.tgz
    version: v0.0.16
  - apiVersion: v2
    appVersion: v0.0.15
    created: "2020-12-11T10:47:14.1653959+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 291f5d5c7ce940833e87619413c0c145a303447cc3c2bb4fbfff04a2bb427ccd
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.15.tgz
    version: v0.0.15
  - apiVersion: v2
    appVersion: v0.0.14
    created: "2020-12-11T10:47:14.1642767+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 989009934d12576b05d3077eed3c2a6ceaad8ed4ed6c695a314682a2a1e47d4e
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.14.tgz
    version: v0.0.14
  - apiVersion: v2
    appVersion: v0.0.13
    created: "2020-12-11T10:47:14.1634216+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: dc573143ea29ffd3329b58e84633c5133101f0b8942c9211a206a8dc4ef88fc2
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.13.tgz
    version: v0.0.13
  - apiVersion: v2
    appVersion: v0.0.12
    created: "2020-12-11T10:47:14.1625953+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 7af2773b32835b8156a4f569b7374904c879243de043ac3609ce4575fe69c7e7
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.12.tgz
    version: v0.0.12
  - apiVersion: v2
    appVersion: v0.0.11
    created: "2020-12-11T10:47:14.1618613+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: bdfded943f784632068d5a7f8cf3767ae87a18aec4b3ec21845d19ccdb12c6ef
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.11.tgz
    version: v0.0.11
  - apiVersion: v2
    appVersion: v0.0.10
    created: "2020-12-11T10:47:14.161003+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 71acba01c305a02afe3237f89c32ca2e9d0048883e6c142e3c6138ff6b6eeb2e
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.10.tgz
    version: v0.0.10
  - apiVersion: v2
    appVersion: v0.0.9
    created: "2020-12-11T10:47:14.1855147+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: 4a812e55a97339181fd90043cafd23752c8986e7591b32db5bb4dbfb53c63f35
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.9.tgz
    version: v0.0.9
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2020-12-11T10:47:14.1843011+02:00"
    description: A Kubernetes-Native Virtual Desktop Infrastructure
    digest: ce0ed4fc65c001750193ab83c470c40f245ee33c7e0884bbf0f48ecdb83ded0c
    name: kvdi
    type: application
    urls:
    - kvdi-v0.0.8.tgz
    version: v0.0.8
generated: "2020-12-11T10:47:14.1587987+02:00"
